In [9]:
import pandas as pd
import numpy as np
df=pd.read_csv('ISL DATASET A  - ISL DATASET A .csv')
df

,PLAYER NAME,TEAM NAME,MATCHES PLAYED,MINUTES PLAYED,GOALS,ASSISTS,SHOTS,CHANCE CREATED,PASSES,SHOTS ON TARGET,TOUCHES,FOULS,FOULS EARNED,YELLOW CARD,RED CARD,AERIAL DUEL WON,COUNTRY,Overall,Potential
0,DIMITROS PETRATOS,MOHUN BAGAN SUPER GIANT,35,3006,18,8,85,86,939,42,1505,38,26,1,0,6,AUSTRALIA,NaN,NaN
1,JASON STEVEN CUMMINGS,MOHUN BAGAN SUPER GIANT,12,793,6,2,18,15,195,11,292,10,5,0,0,8,AUSTRALIA,NaN,NaN
2,ARMANDO SADIKU,MOHUN BAGAN SUPER GIANT,13,645,4,1,24,6,165,10,269,18,8,4,0,8,ALBANIA,NaN,NaN
3,MANVIR SINGH,MOHUN BAGAN SUPER GIANT,122,6815,19,11,130,101,2028,65,3328,136,59,4,0,184,INDIA,62.0,62.0
4,LISTON COLACO,MOHUN BAGAN SUPER GIANT,87,5371,15,15,156,75,1573,81,3054,202,148,4,1,23,INDIA,61.0,64.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,DANIEL LALHLIMPUIA,PUNJAB FC,60,2468,5,4,43,33,606,21,998,68,41,0,0,10,INDIA,53.0,56.0
75,LUKA MAJCEN,PUNJAB FC,18,1514,6,1,25,19,325,14,487,44,24,3,0,21,SLOVENIA,NaN,NaN
76,PRASANTH KARUTHADATHKUNI MOHAN,PUNJAB FC,86,3864,2,4,25,37,975,15,1735,86,47,5,0,22,INDIA,NaN,NaN
77,RANJEET SINGH PANDRE,PUNJAB FC,3,27,0,0,0,0,18,0,23,1,1,0,0,0,INDIA,NaN,NaN
78,WILMAR JORDÁN GIL,PUNJAB FC,22,1297,13,1,44,12,301,26,571,42,27,2,1,34,COLOMBIA,NaN,NaN

In [10]:
# Drop rows with any null values
clean_df = df.dropna()

# Display the new DataFrame

clean_df = clean_df.drop(columns=['Potential'])
print(clean_df)

                 PLAYER NAME                TEAM NAME  MATCHES PLAYED  \
3               MANVIR SINGH  MOHUN BAGAN SUPER GIANT             122
4              LISTON COLACO  MOHUN BAGAN SUPER GIANT              87
11         NANDHAKUMAR SEKAR           EAST BENGAL FC              99
13     SUHAIR VADAKKEPEEDIKA           EAST BENGAL FC              64
15  VISHNU PUTHIYA VALAPPILL           EAST BENGAL FC              14
19              IRFAN YADWAD            CHENNAIYIN FC              12
21                 RAHIM ALI            CHENNAIYIN FC              66
22            VINCY BARRETTO            CHENNAIYIN FC              48
23        HALICHARAN NARZARY             BENGALURU FC             114
24             MONIRUL MOLLA             BENGALURU FC               6
26                ROHIT DANU             BENGALURU FC              43
28      SIVASAKTHI NARAYANAN             BENGALURU FC              42
29             SUNIL CHHETRI             BENGALURU FC             151
30             AAREN D'SILVA             HYDERABAD FC              29
31               AMON LEPCHA             HYDERABAD FC               2
32         AMOSA LALNUNDANGA             HYDERABAD FC               1
33      ARON VANLALRINCHHANA             HYDERABAD FC               6
34              JOSEPH SUNNY             HYDERABAD FC               6
38              KOMAL THATAL            JAMSHEDPUR FC              29
52     BIPIN SINGH THOUNAJAM           MUMBAI CITY FC              97
62              MANVIR SINGH      NORTHEAST UNITED FC              11
64              REDEEM TLANG      NORTHEAST UNITED FC              86
70     JERRY MAWIHMINGTHANGA                ODISHA FC             114
74        DANIEL LALHLIMPUIA                PUNJAB FC              60

    MINUTES PLAYED  GOALS  ASSISTS  SHOTS  CHANCE CREATED  PASSES  \
3             6815     19       11    130             101    2028
4             5371     15       15    156              75    1573
11            7102     15       14     93              82    1876
13            4333      8        6     78              60    1102
15             530      1        1      7               4     146
19             251      0        0     10               3      60
21            3708      8        4     61              40    1067
22            1927      6        2     44              21     451
23            7334      9       15    102             117    2344
24             123      0        0      5               0      18
26            1448      2        2     19              18     374
28            1690      8        3     32              21     313
29           11363     60       11    287             129    3241
30             579      1        1     17               6     180
31              26      0        0      1               0       2
32               1      0        0      0               1       1
33              69      0        0      2               0      35
34             365      0        0      4               2      95
38            1154      2        0     16               5     198
52            7003     24       11    113              93    1811
62             296      0        0      3               5      65
64            4652      9        4     57              54    1394
70            8234     13       20    100             107    2060
74            2468      5        4     43              33     606

    SHOTS ON TARGET  TOUCHES  FOULS  FOULS EARNED  YELLOW CARD  RED CARD  \
3                65     3328    136            59            4         0
4                81     3054    202           148            4         1
11               44     3347    122            66            6         1
13               31     1979    193            68           11         0
15                4      295     16            10            1         0
19                0      117     13             7            4         0
21               23     1795    137            62           11         0
22               17      890     70            47            4         0
23               26     3933    156            81            3         0
24                1       49      6             1            1         0
26                9      721     63            38            3         0
28               17      642     44            23            1         0
29              152     4899    327           144           18         0
30                4      315     21            12            2         0
31                0        5      1             1            0         0
32                0        2      0             0            0         0
33                2       57      3             3            0         0
34                0      139     10             4            1         0
38                7      448     37            23            1         0
52               63     3027    113            49            3         0
62                0      100      7             2            0         0
64               25     2496    170            69           16         1
70               41     3748    244           152           10         0
74               21      998     68            41            0         0

    AERIAL DUEL WON COUNTRY  Overall
3               184   INDIA     62.0
4                23   INDIA     61.0
11               33   INDIA     57.0
13               59   INDIA     58.0
15               20   INDIA     50.0
19                5   INDIA     49.0
21               67   INDIA     58.0
22               20   INDIA     55.0
23               84   INDIA     59.0
24                2   INDIA     51.0
26               12   INDIA     54.0
28                5   INDIA     56.0
29              250   INDIA     67.0
30               31   INDIA     53.0
31                0   INDIA     49.0
32                0   INDIA     48.0
33                0   INDIA     50.0
34                5   INDIA     50.0
38                2   INDIA     53.0
52               30   INDIA     61.0
62                9   INDIA     51.0
64               36   INDIA     56.0
70               36   INDIA     58.0
74               10   INDIA     53.0

In [12]:
clean_df.to_csv('Attacker_withOverall', index=False)